In [1]:
# Basic
import numpy as np
from scipy.linalg import pinv2

$$
\frac{\partial h}{\partial x} \left( \frac{\partial V}{\partial x} \right)^+ \tilde{\dot{V}} = \tilde{\dot{h}}_1 = \frac{\partial h}{\partial x} [ \tilde{f} \; \tilde{g}] [1 \; u]^T \\
\tilde{\dot{h}} = \tilde{\dot{h}}_2 = \frac{\partial h}{\partial x} [ \tilde{f} \; \tilde{g}] [1 \; u]^T
$$

A possible arrangement could be

$$
\frac{\partial h}{\partial x} [ \tilde{f} \; \tilde{g}]  = [e_f \; e_g] = [\tilde{\dot{h}}_1  \; \tilde{\dot{h}}_2 ] \begin{bmatrix} 1& 1\\ u &u
\end{bmatrix}^+
$$


In [2]:

# Random sample values for the components.
u_ext = np.array([[1], [5000]]) # u_ext = [1 u]^T

dhx = np.array([[0, -1, 2]]) # dh/dx
dVx = np.array([[0, 2, 0]])  #dV/dx
dh_est = np.array([[3]]) #dot{h}
dV_est = np.array([[4]]) #dot{V}

eps_fg = np.array([[0.5,0.2],[0.6,0.1],[0.1,0.4]]) # [\eps_f \eps_g]


dh_real = dh_est + dhx.dot(np.dot(eps_fg, u_ext))
dV_real =  dV_est + dVx.dot(np.dot(eps_fg, u_ext))

dhe1 = dh_real - dh_est
dhe2 = dhx.dot(pinv2(dVx)).dot(dV_real - dV_est) 

U = np.hstack([u_ext,u_ext])
Y = np.hstack([dhe1,dhe2])

#e_fg = [e_f, e_g]
e_fg_real = dhx.dot(eps_fg) 
e_fg_est = Y.dot(pinv2(U)) # if pinv2 replaced with pinv, NaN error appears

print('Values expected {}'.format(e_fg_real))
print('Values obtained {}'.format(e_fg_est))



Values expected [[-0.4  0.7]]
Values obtained [[5.99799976e-05 2.99899988e-01]]


In [9]:
# Random initial values
a1 = 2.3
a2 = a1 + 0.01
b1 = 1.3
b2 = b1 + 0.01

u1 = 1000
u2 = 1300


A = np.array([[a1, b1],[a2, b2]])
u_ext = np.array([[1, 1],[u1, u2]])

y = A.dot(u_ext)
y_real = np.diag(np.diag(y))

A_est = y_real.dot(pinv2(u_ext))




In [10]:
A_est

array([[ 5.64330000e+03, -4.34100000e+00],
       [-5.68436667e+03,  5.68436667e+00]])

In [11]:
A

array([[2.3 , 1.3 ],
       [2.31, 1.31]])

In [7]:
np.diag(y)

array([1302.3 , 1705.31])

array([[1302.3 ,    0.  ],
       [   0.  , 1705.31]])

In [4]:
e_fg_real.dot(u_ext)

array([[3499.6]])

In [6]:
e_fg_est.dot(u_ext)

array([[1499.5]])

In [7]:
Y

array([[3499.6, -500.6]])